// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcI7LclYQm0hD_aNTD6GK1N468Jx0Av7s',
    appId: '1:969805668114:web:93088c8699d38a16c75dcb',
    messagingSenderId: '969805668114',
    projectId: 'booking-p2tk',
    authDomain: 'booking-p2tk.firebaseapp.com',
    storageBucket: 'booking-p2tk.firebasestorage.app',
    measurementId: 'G-HY1JX58GFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWYtwhmPXfIYwKk6NsAbXtLaXGjtOesM',
    appId: '1:969805668114:android:151d7b70275628b1c75dcb',
    messagingSenderId: '969805668114',
    projectId: 'booking-p2tk',
    storageBucket: 'booking-p2tk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA80UVdFiHsp1Zln_UMwEAW2cusfsG1g2c',
    appId: '1:969805668114:ios:3b3f45dcec03b1bac75dcb',
    messagingSenderId: '969805668114',
    projectId: 'booking-p2tk',
    storageBucket: 'booking-p2tk.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA80UVdFiHsp1Zln_UMwEAW2cusfsG1g2c',
    appId: '1:969805668114:ios:3b3f45dcec03b1bac75dcb',
    messagingSenderId: '969805668114',
    projectId: 'booking-p2tk',
    storageBucket: 'booking-p2tk.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcI7LclYQm0hD_aNTD6GK1N468Jx0Av7s',
    appId: '1:969805668114:web:a9cd74bea3b83a07c75dcb',
    messagingSenderId: '969805668114',
    projectId: 'booking-p2tk',
    authDomain: 'booking-p2tk.firebaseapp.com',
    storageBucket: 'booking-p2tk.firebasestorage.app',
    measurementId: 'G-FDGQ1HSPKD',
  );
}
