// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA-kUmGT1-20wQuIPEyK2KdrFhdSKXDso',
    appId: '1:907584919152:web:7e0648788761124f3f06b5',
    messagingSenderId: '907584919152',
    projectId: 'quanlidatphongks',
    authDomain: 'quanlidatphongks.firebaseapp.com',
    storageBucket: 'quanlidatphongks.firebasestorage.app',
    measurementId: 'G-TS130Z8KRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5vLbpNx12FV4EgaHS_IBlu7tqvnZpUrc',
    appId: '1:907584919152:android:f535004686644f563f06b5',
    messagingSenderId: '907584919152',
    projectId: 'quanlidatphongks',
    storageBucket: 'quanlidatphongks.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA-kUmGT1-20wQuIPEyK2KdrFhdSKXDso',
    appId: '1:907584919152:web:099f5b1d6e39447a3f06b5',
    messagingSenderId: '907584919152',
    projectId: 'quanlidatphongks',
    authDomain: 'quanlidatphongks.firebaseapp.com',
    storageBucket: 'quanlidatphongks.firebasestorage.app',
    measurementId: 'G-450SFV4JRK',
  );
}
